### PR TITLE
Pte/correct json

### PR DESCRIPTION
**Pull request by PierreTechoueyres**
### Rapid summary
Avoid error when sending json encoded data with non ASCII characters

### What issue does this fix or improve?
Allow sync of cards with non ASCII characters, when the org buffer isn't encoded in UTF-8

### Have you checked and/or added tests?
All tests have been run successfully.

### CODE REVIEW

**Comment by ardumont** [comment]
Hello,

Sounds good, thanks a bunch.

Will take a closer look at this soon and possibly integrate it in the 0.8.1 branch.

Cheers,

**Comment by ardumont** [comment]
> integrate it in the 0.8.1 branch.

Done, thx again.

Cheers,

**Comment by PierreTechoueyres** [comment]
Hello @ardumont,
Have you done the merge ? I don't see it in the repo.
Anyway, thanks for your great work on this project. This make my daily work less boring.

**Comment by ardumont** [comment]
> Have you done the merge ?

No, not merged yet.

> I don't see it in the repo.

Indeed, that's not in the main repo.
It's in my fork (which is historically, the original repo :)

You could see it at https://github.com/ardumont/org-trello/tree/0.8.1.

> Anyway, thanks for your great work on this project.

Thanks.
Thanks for your contribution, that helps ;)

> This make my daily work less boring.

That's cool :)

Cheers,

**Comment by PierreTechoueyres** [comment]
Hello @ardumont,
Any hope you release this branch soon ? I think this could maybe fix some of the encoding problems reported (but I may  be wrong).
Cheers

**Comment by ardumont** [comment]
Hello,

> Any hope you release this branch soon ? I think this could maybe fix some of the encoding problems reported (but I may be wrong).

Thanks for reminding me.
That will definitely help in deciding to push it.

Cheers,

**Comment by ardumont** [comment]
>>    Any hope you release this branch soon ? I think this could maybe fix some of the encoding problems
>> reported (but I may be wrong).

Well, it helped in at least one case, so you were not completely wrong (#379).
And that's good enough for me!

> Thanks for reminding me.
> That will definitely help in deciding to push it.

Indeed.

Cheers,

**Comment by ardumont** [comment]
Closed as #380 contains it and it got finally merged! \m/

**Pull request closed without merging**
