### PR TITLE
Consistently kill line

### PR DESCRIPTION
**Pull request by Jell**
### Rapid summary

When user has `kill-whole-line` setting set to `'t`, sync:ing a remote card with a checkbox would fail (see #270)

### What issue does this fix or improve?

Consistently kill line by locally shadowing the user setting.

### Have you checked and/or added tests?

Not yet

### CODE REVIEW

**Comment by ardumont** [comment]
Ok.

I need to check this custom's def but this sounds reasonable ^^

Awesome

Thx

**Comment by Jell** [comment]
For reference: https://www.gnu.org/software/emacs/manual/html_node/emacs/Killing-by-Lines.html

```
If the variable kill-whole-line is non-nil, C-k at the very beginning of a line kills the entire line including the following newline. This variable is normally nil.
```

**Comment by ardumont** [comment]
> For reference: https://www.gnu.org/software/emacs/manual/html_node/emacs/Killing-by-Lines.html

Thanks.

> If the variable kill-whole-line is non-nil, C-k at the very beginning of a line kills the entire line including the following newline. This variable is normally nil.

And i need to only remove from beginning of line to the end of line.
So indeed, `kill-whole-line` must be nil.
You sir, are awesome ^^

> test? ... Not yet

My original test miss some context to write the checkbox at point. 
That's why this is not captured and that the current test still pass. 
I will update accordingly.

PS: Another confirmation, my `kill-whole-line` is nil.

**Comment by Jell** [comment]
\o/ Thanks for the quick response and the work you did on this project! Keep up the good work! :)

Cheers!

**Pull request merged**
