### PR TITLE
Fix user properties search in agenda view.

### LINKED ISSUE #366: Filter visible cards on user (and tag)
I'm trying to get org-trello to work. Our Trello board currently contains ~300 cards, for a team of ~10 people.

I would love a way to show only the cards assigned to me, or have them show up in a different color, or have a shortcut "go to next card owned by me", or anything like that.

If filter functionality is implemented, it would seem logical to also be able to filter on tags.

I could work on this myself, but have zero elisp experience, and I'd at least need some guiding on how to do it.

### PR DESCRIPTION
**Pull request by sathlan**
### Rapid summary
It's currently not possible to filter card on user in either agenda view (C-c a m) or in filter (C-c / m) because the orgtrello-users property contains "-" which cannot be escaped during filter creation.

Changing "-" to "_" fixes it, and it becomes possible to do:

   C-c a m
   orgtrello_users="mynick"

and have a nice display of your current task.

### What issue does this fix or improve?
This fixes #366.

### Have you checked and/or added tests?
All the test have been refactored to match the new naming convention.

### CODE REVIEW

**Comment by ardumont** [comment]
Hello,

Ok, this sounds fine.

There is still work to be done though (on the top of my head, entry in README about this, migration routine or a way to notify the users that their buffer will be adapted accordingly).

I'll cherry-pick this commit in a 0.8.1 branch though (and iterate over this later on).

Thanks!

Cheers,

.oO(damn! ci is broken again.)

**Comment by sathlan** [comment]
Hum, unrelated CI failure 

   "Dependency request-deferred failed to install: Package `emacs-24.4' is unavailable"

**Comment by ardumont** [comment]
Yes,

> Hum, unrelated CI failure

> "Dependency request-deferred failed to install: Package `emacs-24.4' is
unavailable"

Yes, no worries there, that's what i meant ;)

**Comment by ardumont** [comment]
Hello,

As usual, there is no obligation there.
Just detailing my thought process.

> I'll cherry-pick this commit in a 0.8.1 branch though (and iterate over this later on).

Done

For information, something changed on the ci tooling and that broke it.
This is now fixed.

So this time, the failure is real (due to broken tests on this feature).
Typically, some actual hash computation takes place on some buffer part.
So tests doing those are broken (since text did change).

```
4 unexpected results:
   FAILED  test-orgtrello-buffer--filter-out-known-properties
   FAILED  test-orgtrello-buffer-card-checksum
   FAILED  test-orgtrello-buffer-entity-metadata
   FAILED  test-orgtrello-buffer-org-unknown-drawer-properties
```

I have finally being able to fix my own local setup (well partially) and reproduced it locally.
My local tooling broke without me doing anything and that kind of annoyed me... (and delayed me quite often)

> For the upgrade procedure it does work but the old properties (with the "-") stays in the buffer after the current file properties, so it would have to be clean up.

Yes, that's what i imagined and would like to avoid.

Also, come to think of it, there is now some inconsistency on the org-trello properties.
There remains some that still uses the `-` as separator (`orgtrello-id` for one).
So i think, this needs to be pushed a little further.

> I'll look into the readme to warn the user

There is a [migration chapter](http://org-trello.github.io/migration.html) for that.
The repository is [org-trello/org-trello.github.io](https://github.com/org-trello/org-trello.github.io).

> as maybe a proper cleanup procedure (pointer appreciated here :))

I don't ask you to do it, i just explain my thought process :)

Have some kind of <kbd>M-x org-trello-upgrade-buffer RET</kbd> procedure (or some other name). This would be in charge of replacing the changed keys to what's currently needed.

I prefer to have a manual trigger instead of an automated one to avoid user surprise.
This could be checked in the <kbd>M-x org-trello-check-setup</kbd>...

But all of this would need to be described in the documentation anyway (cf. previous point).

Cheers,

**Comment by ardumont** [comment]
> Have some kind of M-x org-trello-upgrade-buffer RET procedure (or some other name). This would be in charge of replacing the changed keys to what's currently needed.

> I prefer to have a manual trigger instead of an automated one to avoid user surprise.
> This could be checked in the M-x org-trello-check-setup...

I have something similar in 0.8.1.
But not so sure i want that...
Need to think some more about it.

Cheers,

**Pull request closed without merging**
